In [1]:

from lab.postprocessing.toolbox import load_model

In [3]:
model ,loader = load_model("/home/iailab36/aliakbar/rnn-cnn/scripts/results/cifar/resnet/resnet_RNN_dim_10_rec_2/","0718-121833")
model_mlp ,loader_1 = load_model("/home/iailab36/aliakbar/rnn-cnn/scripts/results/cifar/resnet/resnet_RNN_dim_10_rec_2/","0718-121833")

Extracting data/cifar-10-python.tar.gz to data/


In [118]:
for batch in loader.valid:
    input= batch[0].to("cuda:0")
    logits_stacked, final_steps = model(input)
    
    break
logits_stacked[0]

tensor([[-10.2450, -13.1973, -12.7948,  ..., -11.9977, -31.3913,  -9.4050],
        [ -1.7002, -18.1747,  -2.7445,  ..., -16.1180, -10.1669, -13.1498],
        [ -1.5749, -10.0555,   1.2282,  ..., -10.2823,  -5.9543, -13.4654],
        ...,
        [-11.1198, -53.0684,  -5.4558,  ..., -14.3922, -48.5821, -46.0804],
        [ -0.3423,  10.6317,  -5.9400,  ..., -13.8340,  -0.4080,   1.4377],
        [  1.9737,   5.6264,  -9.0477,  ...,  -3.3168,  -1.1589,   8.6727]],
       device='cuda:0')

In [115]:
final_steps=final_steps.cpu().numpy()


AttributeError: 'numpy.ndarray' object has no attribute 'cpu'

In [83]:
logits_stacked[0][0]
import torch

from sklearn.metrics import accuracy_score
prediction = torch.argmax(logits_stacked[0],dim=1, keepdim=True)
actuals= (batch[1].view_as(prediction))
print('Accuracy score: %f' % accuracy_score(actuals.cpu().numpy(), prediction.cpu().numpy()))
pred_labels = prediction.cpu().reshape( [128])
pred_labels

Accuracy score: 0.757812


tensor([6, 0, 2, 7, 0, 6, 5, 4, 5, 2, 8, 6, 8, 7, 9, 8, 4, 5, 9, 5, 8, 6, 9, 9,
        5, 2, 6, 4, 7, 6, 7, 0, 4, 2, 6, 1, 0, 4, 9, 7, 1, 7, 0, 6, 0, 6, 7, 1,
        8, 9, 7, 2, 3, 6, 9, 0, 2, 4, 4, 6, 1, 1, 0, 6, 7, 5, 5, 7, 2, 6, 0, 7,
        6, 2, 9, 2, 2, 8, 2, 9, 7, 7, 2, 2, 6, 8, 9, 7, 6, 0, 1, 1, 5, 0, 8, 0,
        9, 5, 9, 5, 0, 4, 2, 0, 9, 2, 6, 2, 4, 1, 8, 4, 7, 0, 4, 7, 6, 8, 8, 5,
        8, 4, 7, 2, 0, 4, 1, 9])

In [119]:
labels

tensor([6, 0, 2, 3, 3, 6, 3, 3, 5, 6, 0, 6, 8, 3, 9, 0, 4, 5, 9, 3, 8, 6, 7, 9,
        5, 2, 6, 4, 4, 6, 7, 0, 4, 2, 6, 1, 6, 4, 9, 3, 1, 7, 0, 6, 2, 6, 7, 1,
        8, 9, 5, 2, 3, 6, 9, 4, 2, 4, 2, 6, 1, 1, 0, 6, 7, 5, 5, 7, 2, 6, 3, 7,
        6, 2, 9, 4, 2, 8, 2, 9, 7, 7, 2, 2, 6, 8, 9, 3, 6, 0, 1, 2, 5, 0, 8, 0,
        9, 5, 9, 5, 8, 4, 2, 0, 9, 2, 6, 0, 4, 9, 8, 2, 3, 0, 2, 3, 6, 8, 8, 5,
        8, 2, 7, 4, 6, 4, 1, 9])

In [92]:
eq=torch.eq(pred_labels,labels)
cl = np.where(eq.numpy()==False,"Red","Black")
cl

array(['Black', 'Black', 'Black', 'Red', 'Red', 'Black', 'Red', 'Red',
       'Black', 'Red', 'Red', 'Black', 'Black', 'Red', 'Black', 'Red',
       'Black', 'Black', 'Black', 'Red', 'Black', 'Black', 'Red', 'Black',
       'Black', 'Black', 'Black', 'Black', 'Red', 'Black', 'Black',
       'Black', 'Black', 'Black', 'Black', 'Black', 'Red', 'Black',
       'Black', 'Red', 'Black', 'Black', 'Black', 'Black', 'Red', 'Black',
       'Black', 'Black', 'Black', 'Black', 'Red', 'Black', 'Black',
       'Black', 'Black', 'Red', 'Black', 'Black', 'Red', 'Black', 'Black',
       'Black', 'Black', 'Black', 'Black', 'Black', 'Black', 'Black',
       'Black', 'Black', 'Red', 'Black', 'Black', 'Black', 'Black', 'Red',
       'Black', 'Black', 'Black', 'Black', 'Black', 'Black', 'Black',
       'Black', 'Black', 'Black', 'Black', 'Red', 'Black', 'Black',
       'Black', 'Red', 'Black', 'Black', 'Black', 'Black', 'Black',
       'Black', 'Black', 'Black', 'Red', 'Black', 'Black', 'Black',
       'Bl

In [36]:
label_names= ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']

In [1]:
import matplotlib.pyplot as plt
import numpy as np
# take the images data from batch data
images = batch[0].numpy()

# reshape and transpose the images
images = images.reshape(len(images),3,32,32).transpose(0,2,3,1)
# take labels of the images 
labels = batch[1]
# label names of the images
# label_names = meta_data['label_names']

rows, columns = 11, 11
# take random image idex id
# imageId = np.random.randint(0, len(images), rows * columns)
# take images for above random image ids
# images = images[imageId]
# take labels for these images only
# labels = [labels[i] for i in images]

# define figure
fig=plt.figure(figsize=(20, 20))
# visualize these random images
for i in range(1, columns*rows +1):
    fig.add_subplot(rows, columns, i)
    plt.imshow(images[i-1])
    plt.xticks([])
    plt.yticks([])
    plt.title("{}"
          .format(label_names[pred_labels[i-1]]+str(final_steps[i-1]+1)),color=cl[i-1])
fig.tight_layout()
plt.show()

NameError: name 'batch' is not defined